/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, contactNumber: {
                    name: "contactNumber",
                    type: "String",
                    isOptional: true,
                }, passwordHash: {
                    name: "passwordHash",
                    type: "String",
                }, emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    isOptional: true,
                }, image: {
                    name: "image",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "UserStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, hourlyRate: {
                    name: "hourlyRate",
                    type: "Decimal",
                    isOptional: true,
                }, organizationId: {
                    name: "organizationId",
                    type: "String",
                    isOptional: true,
                }, roles: {
                    name: "roles",
                    type: "UserRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, itemProcessingLogs: {
                    name: "itemProcessingLogs",
                    type: "ItemProcessingLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, auditLogs: {
                    name: "auditLogs",
                    type: "AuditLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        role: {
            name: 'Role', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, users: {
                    name: "users",
                    type: "UserRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, permissions: {
                    name: "permissions",
                    type: "RolePermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, stations: {
                    name: "stations",
                    type: "RoleStation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            },
        },
        permission: {
            name: 'Permission', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, action: {
                    name: "action",
                    type: "String",
                }, subject: {
                    name: "subject",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, roles: {
                    name: "roles",
                    type: "RolePermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'permission',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, action_subject: {
                    name: "action_subject",
                    fields: ["action", "subject"]
                },
            },
        },
        userRole: {
            name: 'UserRole', fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'user',
                }, roleId: {
                    name: "roleId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'users',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "roleId" },
                }, assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, assignedBy: {
                    name: "assignedBy",
                    type: "String",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                userId_roleId: {
                    name: "userId_roleId",
                    fields: ["userId", "roleId"]
                },
            },
        },
        rolePermission: {
            name: 'RolePermission', fields: {
                roleId: {
                    name: "roleId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, permissionId: {
                    name: "permissionId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'permission',
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'permissions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "roleId" },
                }, permission: {
                    name: "permission",
                    type: "Permission",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "permissionId" },
                }, assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                },
            }, uniqueConstraints: {
                roleId_permissionId: {
                    name: "roleId_permissionId",
                    fields: ["roleId", "permissionId"]
                },
            },
        },
        customer: {
            name: 'Customer', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, quickbooksCustomerId: {
                    name: "quickbooksCustomerId",
                    type: "String",
                    isOptional: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, contactNumber: {
                    name: "contactNumber",
                    type: "String",
                    isOptional: true,
                }, email: {
                    name: "email",
                    type: "String",
                    isOptional: true,
                }, type: {
                    name: "type",
                    type: "CustomerType",
                }, status: {
                    name: "status",
                    type: "CustomerStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, shippingAddressLine1: {
                    name: "shippingAddressLine1",
                    type: "String",
                    isOptional: true,
                }, shippingAddressLine2: {
                    name: "shippingAddressLine2",
                    type: "String",
                    isOptional: true,
                }, shippingCity: {
                    name: "shippingCity",
                    type: "String",
                    isOptional: true,
                }, shippingState: {
                    name: "shippingState",
                    type: "String",
                    isOptional: true,
                }, shippingZipCode: {
                    name: "shippingZipCode",
                    type: "String",
                    isOptional: true,
                }, shippingCountry: {
                    name: "shippingCountry",
                    type: "String",
                    isOptional: true,
                }, billingAddressLine1: {
                    name: "billingAddressLine1",
                    type: "String",
                    isOptional: true,
                }, billingAddressLine2: {
                    name: "billingAddressLine2",
                    type: "String",
                    isOptional: true,
                }, billingCity: {
                    name: "billingCity",
                    type: "String",
                    isOptional: true,
                }, billingState: {
                    name: "billingState",
                    type: "String",
                    isOptional: true,
                }, billingZipCode: {
                    name: "billingZipCode",
                    type: "String",
                    isOptional: true,
                }, billingCountry: {
                    name: "billingCountry",
                    type: "String",
                    isOptional: true,
                }, orders: {
                    name: "orders",
                    type: "Order",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'customer',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, quickbooksCustomerId: {
                    name: "quickbooksCustomerId",
                    fields: ["quickbooksCustomerId"]
                },
            },
        },
        item: {
            name: 'Item', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, quickbooksItemId: {
                    name: "quickbooksItemId",
                    type: "String",
                    isOptional: true,
                }, name: {
                    name: "name",
                    type: "String",
                }, imageUrl: {
                    name: "imageUrl",
                    type: "String",
                    isOptional: true,
                }, category: {
                    name: "category",
                    type: "String",
                    isOptional: true,
                }, wholesalePrice: {
                    name: "wholesalePrice",
                    type: "Decimal",
                    isOptional: true,
                }, retailPrice: {
                    name: "retailPrice",
                    type: "Decimal",
                    isOptional: true,
                }, cost: {
                    name: "cost",
                    type: "Decimal",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "ItemStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'item',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, quickbooksItemId: {
                    name: "quickbooksItemId",
                    fields: ["quickbooksItemId"]
                },
            },
        },
        station: {
            name: 'Station', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, barcode: {
                    name: "barcode",
                    type: "String",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, roles: {
                    name: "roles",
                    type: "RoleStation",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'station',
                }, itemProcessingLogs: {
                    name: "itemProcessingLogs",
                    type: "ItemProcessingLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'station',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, barcode: {
                    name: "barcode",
                    fields: ["barcode"]
                },
            },
        },
        roleStation: {
            name: 'RoleStation', fields: {
                roleId: {
                    name: "roleId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, stationId: {
                    name: "stationId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'station',
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'stations',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "roleId" },
                }, station: {
                    name: "station",
                    type: "Station",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "stationId" },
                }, assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                },
            }, uniqueConstraints: {
                roleId_stationId: {
                    name: "roleId_stationId",
                    fields: ["roleId", "stationId"]
                },
            },
        },
        order: {
            name: 'Order', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, quickbooksOrderId: {
                    name: "quickbooksOrderId",
                    type: "String",
                    isOptional: true,
                }, customerId: {
                    name: "customerId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'customer',
                }, customer: {
                    name: "customer",
                    type: "Customer",
                    isDataModel: true,
                    backLink: 'orders',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "customerId" },
                }, salesOrderNumber: {
                    name: "salesOrderNumber",
                    type: "String",
                    isOptional: true,
                }, purchaseOrderNumber: {
                    name: "purchaseOrderNumber",
                    type: "String",
                    isOptional: true,
                }, contactEmail: {
                    name: "contactEmail",
                    type: "String",
                }, contactPhoneNumber: {
                    name: "contactPhoneNumber",
                    type: "String",
                    isOptional: true,
                }, billingAddressLine1: {
                    name: "billingAddressLine1",
                    type: "String",
                    isOptional: true,
                }, billingAddressLine2: {
                    name: "billingAddressLine2",
                    type: "String",
                    isOptional: true,
                }, billingCity: {
                    name: "billingCity",
                    type: "String",
                    isOptional: true,
                }, billingState: {
                    name: "billingState",
                    type: "String",
                    isOptional: true,
                }, billingZipCode: {
                    name: "billingZipCode",
                    type: "String",
                    isOptional: true,
                }, billingCountry: {
                    name: "billingCountry",
                    type: "String",
                    isOptional: true,
                }, shippingAddressLine1: {
                    name: "shippingAddressLine1",
                    type: "String",
                    isOptional: true,
                }, shippingAddressLine2: {
                    name: "shippingAddressLine2",
                    type: "String",
                    isOptional: true,
                }, shippingCity: {
                    name: "shippingCity",
                    type: "String",
                    isOptional: true,
                }, shippingState: {
                    name: "shippingState",
                    type: "String",
                    isOptional: true,
                }, shippingZipCode: {
                    name: "shippingZipCode",
                    type: "String",
                    isOptional: true,
                }, shippingCountry: {
                    name: "shippingCountry",
                    type: "String",
                    isOptional: true,
                }, orderStatus: {
                    name: "orderStatus",
                    type: "OrderSystemStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, barcode: {
                    name: "barcode",
                    type: "String",
                    isOptional: true,
                }, approvedAt: {
                    name: "approvedAt",
                    type: "DateTime",
                    isOptional: true,
                }, readyToShipAt: {
                    name: "readyToShipAt",
                    type: "DateTime",
                    isOptional: true,
                }, shippedAt: {
                    name: "shippedAt",
                    type: "DateTime",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, orderItems: {
                    name: "orderItems",
                    type: "OrderItem",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'order',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, quickbooksOrderId: {
                    name: "quickbooksOrderId",
                    fields: ["quickbooksOrderId"]
                }, barcode: {
                    name: "barcode",
                    fields: ["barcode"]
                },
            },
        },
        orderItem: {
            name: 'OrderItem', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, orderId: {
                    name: "orderId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'order',
                }, order: {
                    name: "order",
                    type: "Order",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderId" },
                }, itemId: {
                    name: "itemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'item',
                }, item: {
                    name: "item",
                    type: "Item",
                    isDataModel: true,
                    backLink: 'orderItems',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "itemId" },
                }, quickbooksOrderLineId: {
                    name: "quickbooksOrderLineId",
                    type: "String",
                    isOptional: true,
                }, quantity: {
                    name: "quantity",
                    type: "Int",
                }, pricePerItem: {
                    name: "pricePerItem",
                    type: "Decimal",
                }, itemStatus: {
                    name: "itemStatus",
                    type: "OrderItemProcessingStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, itemProcessingLogs: {
                    name: "itemProcessingLogs",
                    type: "ItemProcessingLog",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'orderItem',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, quickbooksOrderLineId: {
                    name: "quickbooksOrderLineId",
                    fields: ["quickbooksOrderLineId"]
                },
            },
        },
        itemProcessingLog: {
            name: 'ItemProcessingLog', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, orderItemId: {
                    name: "orderItemId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'orderItem',
                }, orderItem: {
                    name: "orderItem",
                    type: "OrderItem",
                    isDataModel: true,
                    backLink: 'itemProcessingLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "orderItemId" },
                }, stationId: {
                    name: "stationId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'station',
                }, station: {
                    name: "station",
                    type: "Station",
                    isDataModel: true,
                    backLink: 'itemProcessingLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "stationId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'itemProcessingLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, startTime: {
                    name: "startTime",
                    type: "DateTime",
                }, endTime: {
                    name: "endTime",
                    type: "DateTime",
                    isOptional: true,
                }, durationInSeconds: {
                    name: "durationInSeconds",
                    type: "Int",
                    isOptional: true,
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        auditLog: {
            name: 'AuditLog', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'auditLogs',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, action: {
                    name: "action",
                    type: "String",
                }, entityName: {
                    name: "entityName",
                    type: "String",
                    isOptional: true,
                }, entityId: {
                    name: "entityId",
                    type: "String",
                    isOptional: true,
                }, oldValue: {
                    name: "oldValue",
                    type: "Json",
                    isOptional: true,
                }, newValue: {
                    name: "newValue",
                    type: "Json",
                    isOptional: true,
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, token: {
                    name: "token",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, token: {
                    name: "token",
                    fields: ["token"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, accountId: {
                    name: "accountId",
                    type: "String",
                }, providerId: {
                    name: "providerId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, accessToken: {
                    name: "accessToken",
                    type: "String",
                    isOptional: true,
                }, refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    isOptional: true,
                }, idToken: {
                    name: "idToken",
                    type: "String",
                    isOptional: true,
                }, accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, providerId_accountId: {
                    name: "providerId_accountId",
                    fields: ["providerId", "accountId"]
                },
            },
        },
        verification: {
            name: 'Verification', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, identifier: {
                    name: "identifier",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "String",
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, value: {
                    name: "value",
                    fields: ["value"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['UserRole', 'Session', 'Account'],
        role: ['UserRole', 'RolePermission', 'RoleStation'],
        permission: ['RolePermission'],
        station: ['RoleStation'],
        order: ['OrderItem'],
        orderItem: ['ItemProcessingLog'],

    },
    authModel: 'User'

};
export default metadata;
