/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Order } from "@prisma-app/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderCreateArgs, DefaultError, Order, true>('Order', 'POST', `${endpoint}/order/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Order', 'POST', `${endpoint}/order/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyOrder<TArgs extends Prisma.OrderFindManyArgs, TQueryFnData = Array<Prisma.OrderGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/findMany`, args, options, fetch);
}

export function useInfiniteFindManyOrder<TArgs extends Prisma.OrderFindManyArgs, TQueryFnData = Array<Prisma.OrderGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/findMany`, args, options, fetch);
}

export function useFindUniqueOrder<TArgs extends Prisma.OrderFindUniqueArgs, TQueryFnData = Prisma.OrderGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/findUnique`, args, options, fetch);
}

export function useFindFirstOrder<TArgs extends Prisma.OrderFindFirstArgs, TQueryFnData = Prisma.OrderGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/findFirst`, args, options, fetch);
}

export function useUpdateOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderUpdateArgs, DefaultError, Order, true>('Order', 'PUT', `${endpoint}/order/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Order', 'PUT', `${endpoint}/order/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderUpsertArgs, DefaultError, Order, true>('Order', 'POST', `${endpoint}/order/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Order | undefined), DefaultError, Prisma.OrderDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderDeleteArgs, DefaultError, Order, true>('Order', 'DELETE', `${endpoint}/order/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.OrderDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Order, Prisma.OrderGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyOrder(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.OrderDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.OrderDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Order', 'DELETE', `${endpoint}/order/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.OrderDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.OrderDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.OrderDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateOrder<TArgs extends Prisma.OrderAggregateArgs, TQueryFnData = Prisma.GetOrderAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/aggregate`, args, options, fetch);
}

export function useGroupByOrder<TArgs extends Prisma.OrderGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OrderGroupByArgs['orderBy'] } : { orderBy?: Prisma.OrderGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.OrderGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.OrderGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.OrderGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.OrderGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.OrderGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/groupBy`, args, options, fetch);
}

export function useCountOrder<TArgs extends Prisma.OrderCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.OrderCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.OrderCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.OrderCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Order', `${endpoint}/order/count`, args, options, fetch);
}
import type { OrderSystemStatus, OrderPriority } from '@prisma-app/client';

export function useCheckOrder<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; quickbooksOrderId?: string; customerId?: string; salesOrderNumber?: string; purchaseOrderNumber?: string; poNumber?: string; estimateId?: string; trackingNumber?: string; emailStatus?: string; customerMemo?: string; contactEmail?: string; contactPhoneNumber?: string; billingAddressLine1?: string; billingAddressLine2?: string; billingCity?: string; billingState?: string; billingZipCode?: string; billingCountry?: string; shippingAddressLine1?: string; shippingAddressLine2?: string; shippingCity?: string; shippingState?: string; shippingZipCode?: string; shippingCountry?: string; orderStatus?: OrderSystemStatus; priority?: OrderPriority; barcode?: string; notes?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Order', `${endpoint}/order/check`, args, options, fetch);
}
