/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, ProductAttribute } from "@prisma-app/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeCreateArgs, DefaultError, ProductAttribute, true>('ProductAttribute', 'POST', `${endpoint}/productAttribute/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductAttribute', 'POST', `${endpoint}/productAttribute/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyProductAttribute<TArgs extends Prisma.ProductAttributeFindManyArgs, TQueryFnData = Array<Prisma.ProductAttributeGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/findMany`, args, options, fetch);
}

export function useInfiniteFindManyProductAttribute<TArgs extends Prisma.ProductAttributeFindManyArgs, TQueryFnData = Array<Prisma.ProductAttributeGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/findMany`, args, options, fetch);
}

export function useFindUniqueProductAttribute<TArgs extends Prisma.ProductAttributeFindUniqueArgs, TQueryFnData = Prisma.ProductAttributeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/findUnique`, args, options, fetch);
}

export function useFindFirstProductAttribute<TArgs extends Prisma.ProductAttributeFindFirstArgs, TQueryFnData = Prisma.ProductAttributeGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/findFirst`, args, options, fetch);
}

export function useUpdateProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeUpdateArgs, DefaultError, ProductAttribute, true>('ProductAttribute', 'PUT', `${endpoint}/productAttribute/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductAttribute', 'PUT', `${endpoint}/productAttribute/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeUpsertArgs, DefaultError, ProductAttribute, true>('ProductAttribute', 'POST', `${endpoint}/productAttribute/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(ProductAttribute | undefined), DefaultError, Prisma.ProductAttributeDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeDeleteArgs, DefaultError, ProductAttribute, true>('ProductAttribute', 'DELETE', `${endpoint}/productAttribute/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ProductAttribute, Prisma.ProductAttributeGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyProductAttribute(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ProductAttributeDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ProductAttributeDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ProductAttribute', 'DELETE', `${endpoint}/productAttribute/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ProductAttributeDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ProductAttributeDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProductAttribute<TArgs extends Prisma.ProductAttributeAggregateArgs, TQueryFnData = Prisma.GetProductAttributeAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/aggregate`, args, options, fetch);
}

export function useGroupByProductAttribute<TArgs extends Prisma.ProductAttributeGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ProductAttributeGroupByArgs['orderBy'] } : { orderBy?: Prisma.ProductAttributeGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ProductAttributeGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.ProductAttributeGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.ProductAttributeGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ProductAttributeGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ProductAttributeGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ProductAttributeGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/groupBy`, args, options, fetch);
}

export function useCountProductAttribute<TArgs extends Prisma.ProductAttributeCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ProductAttributeCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.ProductAttributeCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ProductAttribute', `${endpoint}/productAttribute/count`, args, options, fetch);
}
import type { ProductType, SkirtType, TieDownPlacement } from '@prisma-app/client';

export function useCheckProductAttribute<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; orderItemId?: string; productType?: ProductType; color?: string; size?: string; shape?: string; radiusSize?: string; length?: string; width?: string; skirtLength?: string; skirtType?: SkirtType; tieDownsQty?: string; tieDownPlacement?: TieDownPlacement; distance?: string; tieDownLength?: string; poNumber?: string; notes?: string; foamUpgrade?: string; doublePlasticWrapUpgrade?: string; webbingUpgrade?: string; metalForLifterUpgrade?: string; steamStopperUpgrade?: string; fabricUpgrade?: string; extraHandleQty?: string; extraLongSkirt?: string; packaging?: boolean; verified?: boolean; isParsedFromDescription?: boolean; parsingErrors?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ProductAttribute', `${endpoint}/productAttribute/check`, args, options, fetch);
}
