/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, QuickBooksIntegration } from "@prisma-app/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationCreateArgs, DefaultError, QuickBooksIntegration, true>('QuickBooksIntegration', 'POST', `${endpoint}/quickBooksIntegration/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('QuickBooksIntegration', 'POST', `${endpoint}/quickBooksIntegration/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationFindManyArgs, TQueryFnData = Array<Prisma.QuickBooksIntegrationGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/findMany`, args, options, fetch);
}

export function useInfiniteFindManyQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationFindManyArgs, TQueryFnData = Array<Prisma.QuickBooksIntegrationGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/findMany`, args, options, fetch);
}

export function useFindUniqueQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationFindUniqueArgs, TQueryFnData = Prisma.QuickBooksIntegrationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/findUnique`, args, options, fetch);
}

export function useFindFirstQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationFindFirstArgs, TQueryFnData = Prisma.QuickBooksIntegrationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/findFirst`, args, options, fetch);
}

export function useUpdateQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationUpdateArgs, DefaultError, QuickBooksIntegration, true>('QuickBooksIntegration', 'PUT', `${endpoint}/quickBooksIntegration/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('QuickBooksIntegration', 'PUT', `${endpoint}/quickBooksIntegration/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationUpsertArgs, DefaultError, QuickBooksIntegration, true>('QuickBooksIntegration', 'POST', `${endpoint}/quickBooksIntegration/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(QuickBooksIntegration | undefined), DefaultError, Prisma.QuickBooksIntegrationDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationDeleteArgs, DefaultError, QuickBooksIntegration, true>('QuickBooksIntegration', 'DELETE', `${endpoint}/quickBooksIntegration/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, QuickBooksIntegration, Prisma.QuickBooksIntegrationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyQuickBooksIntegration(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.QuickBooksIntegrationDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.QuickBooksIntegrationDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('QuickBooksIntegration', 'DELETE', `${endpoint}/quickBooksIntegration/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.QuickBooksIntegrationDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.QuickBooksIntegrationDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationAggregateArgs, TQueryFnData = Prisma.GetQuickBooksIntegrationAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/aggregate`, args, options, fetch);
}

export function useGroupByQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.QuickBooksIntegrationGroupByArgs['orderBy'] } : { orderBy?: Prisma.QuickBooksIntegrationGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.QuickBooksIntegrationGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.QuickBooksIntegrationGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.QuickBooksIntegrationGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.QuickBooksIntegrationGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.QuickBooksIntegrationGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.QuickBooksIntegrationGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/groupBy`, args, options, fetch);
}

export function useCountQuickBooksIntegration<TArgs extends Prisma.QuickBooksIntegrationCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.QuickBooksIntegrationCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.QuickBooksIntegrationCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/count`, args, options, fetch);
}

export function useCheckQuickBooksIntegration<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; companyId?: string; accessToken?: string; refreshToken?: string; isActive?: boolean }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('QuickBooksIntegration', `${endpoint}/quickBooksIntegration/check`, args, options, fetch);
}
